// Local development mode – no Lambda calls
console.log(">>> Local mode: loading summary from local JSON file only");

const fileInput = document.getElementById('file-upload');
const uploadBtn = document.getElementById('upload-btn');
const statusMessage = document.getElementById('status-message');
const summaryText = document.getElementById('summary-text');
const downloadBtn = document.getElementById('download-btn');

// Update status message in the UI
function updateStatus(message, isError = false) {
    statusMessage.textContent = message;
    statusMessage.style.color = isError ? 'red' : 'green';
    console.log(">>> Status update:", message, "Error?", isError);
}

// Extract metadata from raw string
function parseMetadata(rawText) {
    const metadata = {};
    const versionMatch = rawText.match(/model_version='([^']+)'/);
    if (versionMatch) metadata.model_version = versionMatch[1];

    const responseMatch = rawText.match(/response_id='([^']+)'/);
    if (responseMatch) metadata.response_id = responseMatch[1];

    const tokensMatch = rawText.match(/total_token_count=(\d+)/);
    if (tokensMatch) metadata.total_token_count = tokensMatch[1];

    return metadata;
}

// Render summary content into the DOM
function renderSummary(summaryData) {
    let html = "";

    if (summaryData.sections) {
        summaryData.sections.forEach(section => {
            html += `<h3 style="margin-top:20px; font-weight:bold;">${section.title}</h3>`;
            html += "<ul>";
            section.bullets.forEach(bullet => {
                html += `<li>${bullet}</li>`;
            });
            html += "</ul>";
        });
    }

    // Metadata filtering and translation
    if (summaryData.raw) {
        const meta = parseMetadata(summaryData.raw);
        html += `<div style="font-size:10px; color:gray; text-align:right; margin-top:20px;">`;
        if (meta.model_version) html += `גרסת מודל: ${meta.model_version}<br>`;
        if (meta.response_id) html += `מזהה תשובה: ${meta.response_id}<br>`;
        if (meta.total_token_count) html += `מספר טוקנים: ${meta.total_token_count}<br>`;
        html += `</div>`;
    }

    summaryText.innerHTML = html;

    // שמירה גלובלית לשימוש ב-PDF
    window.currentSummaryData = summaryData;
}

// Load summary from local JSON file based on uploaded audio filename
async function loadLocalSummary(fileName) {
    try {
        const summaryFileName = fileName + ".summary.json";
        const resp = await fetch(`/uploads/${summaryFileName}`);
        if (!resp.ok) throw new Error("Failed to fetch summary file: " + resp.status);

        const summaryData = await resp.json();
        console.log(">>> Local summary data:", summaryData);

        renderSummary(summaryData);
        updateStatus("Summary successfully loaded from local file!");
    } catch (err) {
        console.error(">>> Error loading local summary:", err);
        updateStatus("Failed to load local summary: " + err.message, true);
    }
}

// Handle upload button click – simulate summary loading
uploadBtn.addEventListener('click', () => {
    const file = fileInput.files[0];
    if (!file) {
        updateStatus("Please select an audio file.", true);
        return;
    }
    console.log(">>> Selected file:", file.name);
    updateStatus("Local mode: searching for summary JSON...", false);
    loadLocalSummary(file.name);
});

// Reverse Hebrew text for RTL rendering in jsPDF
function reverseHebrewLine(line) {
    return line.split('').reverse().join('');
}

downloadBtn.addEventListener('click', () => {
    console.log(">>> Starting PDF generation");
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF({ orientation: 'p', unit: 'pt', format: 'a4' });

    // Load all fonts from font-loader.js
    loadFonts(doc);
    console.log(doc.getFontList());

    // Set default font (NotoSansHebrew Regular)
    doc.setFont("NotoSansHebrew", "regular");
    doc.setFontSize(12);

    let y = 40;
    const margin = 40;
    const maxWidth = 500;
    const xRight = margin + maxWidth;

    // Small header top-left (English only to avoid bidi issues)
    doc.setFontSize(10);
    doc.text("Generated by serverless-gemini-agent by Rene", margin, y, { align: "left" });
    y += 30;

    // Process summary sections from DOM
    const sections = summaryText.querySelectorAll("h3, ul");
    sections.forEach(el => {
        if (el.tagName === "H3") {
            doc.setFontSize(14);
            doc.setFont("NotoSansHebrew", "bold"); // use bold variant
            const title = reverseHebrewLine(el.textContent.trim());
            doc.text(title, xRight, y, { align: "right" });
            doc.setFont("NotoSansHebrew", "regular");
            y += 24;
        } else if (el.tagName === "UL") {
            doc.setFontSize(12);
            el.querySelectorAll("li").forEach(li => {
                const text = reverseHebrewLine(li.textContent.trim());
                const bullet = text + " •";
                const lines = doc.splitTextToSize(bullet, maxWidth);
                lines.forEach(line => {
                    doc.text(line, xRight, y, { align: "right" });
                    y += 18;
                });
            });
            y += 10;
        }
    });

    // Metadata block – use raw summaryData saved globally
    if (window.currentSummaryData && window.currentSummaryData.raw) {
        const meta = parseMetadata(window.currentSummaryData.raw);

        doc.setFontSize(10);
        doc.setTextColor(128, 128, 128); // אפור

        const spacing = 8;

        const drawMetaLine = (labelHebrew, value) => {
            const label = reverseHebrewLine(labelHebrew); // הכותרת בעברית הפוכה
            const valueStr = String(value);

            const labelWidth = doc.getTextWidth(label);
            const valueX = xRight - labelWidth - spacing;

            // הצגת הכותרת בעברית בצד ימין
            doc.text(label, xRight, y, { align: "right" });

            // הצגת הערך משמאל לה
            doc.text(valueStr, valueX, y, { align: "right" });

            y += 12;
        };

        if (meta.model_version) {
            drawMetaLine("גרסת מודל:", meta.model_version);
        }
        if (meta.response_id) {
            drawMetaLine("מזהה תשובה:", meta.response_id);
        }
        if (meta.total_token_count) {
            drawMetaLine("מספר טוקנים:", meta.total_token_count);
        }

        doc.setTextColor(0, 0, 0); // החזרת צבע שחור לטקסט הבא
    }





    doc.save("summary.pdf");
    console.log(">>> PDF generated and saved as summary.pdf");
});
